# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99b6111e86e546f1acae0fa95409a22233d3a344ae5617365b733cdf7103a3f08769ed29500f360586cc2ea74babb6aeb5bcc33b8a19bc043bcc6f334923f347

test:
  secret_key_base: fe5071cb263ea6b4d6d5ea7d457da99b61eff26d93e3aa32dc4f8e99bfc6b991785828c5c16341f5ee7b24ef29eeab211dfd3f22da57d4e204c5af6be205fd2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
